# Generated by Django 6.0.5 on 2026-05-29 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=11)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('warehouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Warehouses',
                'db_table': 'warehouses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('weight_per_unit_kg', models.DecimalField(decimal_places=3, max_digits=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categories')),
            ],
            options={
                'verbose_name_plural': 'Items',
                'db_table': 'items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DisasterZones',
            fields=[
                ('zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('severity_level', models.CharField(max_length=8)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('population_affected', models.IntegerField(blank=True, null=True)),
                ('is_active', models.IntegerField()),
                ('logged_at', models.DateTimeField()),
                ('reported_by', models.ForeignKey(db_column='reported_by', on_delete=django.db.models.deletion.DO_NOTHING, to='core.users')),
            ],
            options={
                'verbose_name_plural': 'Disaster Zones',
                'db_table': 'disaster_zones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuditLogs',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.IntegerField()),
                ('action', models.CharField(max_length=6)),
                ('changed_at', models.DateTimeField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.users')),
            ],
            options={
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=11)),
                ('assigned_driver', models.ForeignKey(blank=True, db_column='assigned_driver', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.users')),
            ],
            options={
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DispatchLogs',
            fields=[
                ('dispatch_id', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.CharField(max_length=8)),
                ('status', models.CharField(max_length=9)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.disasterzones')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.users')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.vehicles')),
            ],
            options={
                'verbose_name_plural': 'Dispatch Logs',
                'db_table': 'dispatch_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WarehouseInventory',
            fields=[
                ('pk', models.CompositePrimaryKey('warehouse_id', 'item_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('quantity_in_stock', models.IntegerField()),
                ('last_updated', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.items')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.warehouses')),
            ],
            options={
                'verbose_name_plural': 'Warehouse Inventory',
                'db_table': 'warehouse_inventory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DispatchLineItems',
            fields=[
                ('line_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_dispatched', models.IntegerField()),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.dispatchlogs')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.items')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.warehouses')),
            ],
            options={
                'verbose_name_plural': 'Dispatch Line Items',
                'db_table': 'dispatch_line_items',
                'managed': True,
            },
        ),
    ]
